document.addEventListener("DOMContentLoaded", () => {

  const saiQuotes = [
  "The greatest fear man can have is the fear of losing God's love.",
  "Too much food results in dullness of mind.",
  "A language is as sweet as the tongues of the speakers.",
  "Every experience drawn through the senses has an effect on one's health.",
  "Love all beings; that is enough.",
  "Discipline is the mark of intelligent living.",
  "When calamity approaches, discrimination departs.",
  "A man's well-being depends upon his degree of contentment.",
  "God is all names and all forms.",
  "Follow the Master, face the devil, fight to the end, finish the game.",
  "Real happiness lies within you.",
  "All things in creation are subject to the law of change, and man too is subject to this law.",
  "Renunciation is the power of battling evil forces and holding the mind in check.",
  "The teachers of tomorrow are the students of today.",
  "God is not to be spoken of as coming down or going up, since He is everywhere.",
  "Learn to speak what you feel, and act what you speak.",
  "The unmistakable mark of a wise man is love for all humanity.",
  "Each man carries his destiny in his own hands.",
  "Whenever and wherever you put yourself in touch with God, that is meditation.",
  "Small minds select narrow roads; expand your vision and take the broad road of service.",
  "Silence is the speech of the spiritual seeker.",
  "Service springs out of love and scatters love in profusion.",
  "Ignorance is the most important cause of sorrow.",
  "Once we surrender our mind completely to God, He takes care of us in every way.",
  "Have constructive thoughts, consoling words, and compassionate acts.",
  "Where there is faith, there is love; where there is love, there is peace; where there is peace, there is God; where there is God, there is bliss.",
  "The end of knowledge is love. The end of education is character.",
  "Love is the scarcest article today.",
  "The sense of 'mine, not thine' is the root of all evil.",
  "All spiritual practice must remove the husk and reveal the kernel.",
  "The mind fixed in awareness of the One is stable like a rock.",
  "Love lives by giving and forgiving; self lives by getting and forgetting.",
  "God is the doer; you are but the instrument.",
  "The heart must be ploughed by repetition of God's name.",
  "God is neither distant nor distinct from you.",
  "To know God means to love God.",
  "Harmony in the home brings order in the nation and peace in the world.",
  "The beauty of life depends upon good habits.",
  "Good company helps cultivate good qualities.",
  "You cannot see Me, but I am the light you see by.",
  "Be ever watchful to take in more and more of God.",
  "If you honour your mother, the Mother of the Universe will guard you.",
  "The same divine current activates all.",
  "God gave you time, space, skill, chance, and fortune. Why feel like the doer?",
  "Make the home a seat of harmony.",
  "Accept whatever God gives you as His best gift.",
  "Unity is divinity; purity is enlightenment.",
  "Always respect another's opinion and point of view.",
  "Food should be balanced, not too salty, hot, bitter, sweet, or sour.",
  "Reason prevails when arguments are free from anger.",
  "Take failure and victory calmly.",
  "There should be no discrimination based on nationality, caste, age, or sex.",
  "Your thoughts, words, and deeds shape others.",
  "God is One without a second.",
  "The service of man is the only means to serve God.",
  "Peace rooted in the heart can never be shaken.",
  "As close as you are to God, so close is God to you.",
  "Immortality is the fruit of sacrifice.",
  "The grace of God is like insurance; it helps without limit.",
  "When you cannot do good, at least desist from doing evil.",
  "Love seeks no reward; love is its own reward.",
  "The joy you cause in the heart of God is the only worthwhile achievement.",
  "Be in the world, but do not let the world be in you.",
  "Truth has no fear; untruth trembles at every shadow.",
  "Be simple and sincere.",
  "The mind sees separateness; love sees unity.",
  "God is the life-breath of every soul.",
  "Being a good example is the best form of service.",
  "Friendship is the expression of unshakable love.",
  "Money comes and goes; morality comes and grows.",
  "God first, the world next, myself last.",
  "Try to conduct yourself without injuring others.",
  "Poisonous words wound more fatally than arrows.",
  "Patience is all the strength man needs.",
  "With effort and prayer, destiny can be attained.",
  "Welcome tests; they ensure progress.",
  "What is offered to God is free from all defects.",
  "Spiritual progress is right living and good conduct.",
  "A nation without control over its senses cannot thrive.",
  "I am you; you are Me. Know this and be free.",
  "Teachers must be examples of love and truth.",
  "Each country is a room in the mansion of God.",
  "Man has both a mind to think and a heart to act.",
  "Love must express itself as service.",
  "The wise are those who know the Self.",
  "Persist and win by recollecting the Lord.",
  "Man fulfills his mission when he sees divinity in all.",
  "Devotion is not a uniform worn on special days.",
  "The journey ends where it began, from self to self.",
  "Duty with love is desirable; love without duty is divine.",
  "When people become good, the world becomes good.",
  "Practice the vocabulary of love; unlearn the language of hate.",
  "God is in you, around you, behind you, above you, and beside you.",
  "Helping those in need is the highest righteousness.",
  "Surrendering the fruit of action to the Lord is real sacrifice.",
  "My birthday is the day divinity blossoms in your heart.",
  "Education should build character.",
  "Truth alone is one's real friend.",
  "Faith is our life-breath; without faith, life is impossible."
];

  const quoteEl = document.getElementById("quote");

  quoteEl.textContent =
    saiQuotes[Math.floor(Math.random() * saiQuotes.length)];
});
